import time

lista_passageiros= ['Piloto', 'Chefe de serviço','Policial','Oficial1','Oficial2','Comissaria1','Comissaria2','Presidiario']
fortwo = []
aviao = []
terminal = ['Piloto', 'Chefe de serviço','Policial','Oficial1','Oficial2','Comissaria1','Comissaria2','Presidiario']
num_viagem = 0

def passageiros_fortwo():
    global num_viagem
    num_viagem += 1
    print(f'\n====== VIAGEM NUMERO {num_viagem} =====\n')
    time.sleep(1)

for viagem in range(1,8):
    if viagem == 1:
        passageiros_fortwo()
        print(f'Estão no terminal {terminal}')
        print(f'Embarcaram no fortwo o {lista_passageiros[0]} e o {lista_passageiros[3]} ')
        fortwo.append(lista_passageiros[0])
        fortwo.append(lista_passageiros[3])
        terminal.remove('Piloto')
        terminal.remove('Oficial1')
        print(f'Ficaram no terminal {terminal}')
        print('Fortwo saiu em direção ao avião')
        time.sleep(1)
        print(f'Fortwo chegou ao avião e o {fortwo[1]} desembarcou')
        aviao.append(fortwo[1])
        fortwo.remove('Oficial1')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retorna para o terminal de embarque dirigindo o carro')
        time.sleep(1)
    elif viagem == 2:
        passageiros_fortwo()
        print(f'Fortwo chegou ao terminal de embarque e o {lista_passageiros[4]} embarcou')
        fortwo.append(lista_passageiros[4])
        print(f'Estão no fortwo o {fortwo[0]} e o {fortwo[1]}')
        terminal.remove('Oficial2')
        print(f'Ficaram no terminal {terminal}')
        print('Fortwo sai em direção ao avião')
        time.sleep(1)
        print(f'Fortwo chegou ao avião e o {fortwo[1]} desembarcou')
        aviao.append(fortwo[1])
        fortwo.remove('Oficial2')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retorna para o terminal de embarque dirigindo o carro')
        time.sleep(1)
    elif viagem == 3:
        passageiros_fortwo()
        print(f'O fortwo chegou ao terminal de embarque e o {fortwo[0]} desembarcou')
        terminal.append(fortwo[0])
        fortwo.clear()
        print(f'Embarcaram no fortwo o {lista_passageiros[1]} e a {lista_passageiros[5]}')
        fortwo.append(lista_passageiros[1])
        fortwo.append(lista_passageiros[5])
        terminal.remove('Chefe de serviço')
        terminal.remove('Comissaria1')
        print(f'Ficaram no terminal {terminal}')
        print('Fortwo saiu em direção ao avião')
        time.sleep(1)
        print(f'Fortwo chegou ao avião e a {fortwo[1]} desembarcou')
        aviao.append(fortwo[1])
        fortwo.remove('Comissaria1')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retorna para o terminal de embarque com o carro')
        time.sleep(1)
    elif viagem == 4:
        passageiros_fortwo()
        print(f'O fortwo chegou ao terminal de embarque o a {lista_passageiros[6]} embarcou')
        fortwo.append(lista_passageiros[6])
        print(f'Estão no fortwo o {lista_passageiros[1]} e a {lista_passageiros[6]}')
        terminal.remove('Comissaria2')
        print(f'Ficaram no terminal {terminal}')
        print(f'Fortwo sai em direção ao avião')
        time.sleep(1)
        print(f'Fortwo chegou ao avião e a {fortwo[1]} desembarcou')
        aviao.append(fortwo[1])
        fortwo.remove('Comissaria2')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retornou para o terminal de embarque dirigindo o carro')
        time.sleep(1)
    elif viagem == 5:
        passageiros_fortwo()
        print(f'O fortwo chegou ao terminal de embarque e o {lista_passageiros[0]} embarcou')
        fortwo.append(lista_passageiros[0])
        print(f'Estão no fortwo {fortwo}')
        terminal.remove('Piloto')
        print(f'Ficaram no terminal {terminal}')
        print(f'Fortwo sai em direção ao avião')
        time.sleep(1)
        print(f'O fortwo chegou ao avião e o {fortwo[0]} desembarcou')
        aviao.append(fortwo[0])
        fortwo.remove('Chefe de serviço')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retornou para o terminal de embarque dirigindo o carro')
        time.sleep(1)
    elif viagem == 6:
        passageiros_fortwo()
        print(f'O fortwo chegou ao terminal de embarque e o {fortwo[0]} desembarcou')
        terminal.append(fortwo[0])
        fortwo.clear()
        print(f'Embarcaram no fortwo o {lista_passageiros[2]} e o {lista_passageiros[7]}')
        fortwo.append(lista_passageiros[2])
        fortwo.append(lista_passageiros[7])
        terminal.remove('Policial')
        terminal.remove('Presidiario')
        print(f'Ficou apenas o {terminal} no terminal de embarque')
        print('Fortwo saiu em direção ao avião')
        time.sleep(1)
        print(f'Fortwo chegou ao avião e o {fortwo[0]} e o {fortwo[1]} desembarcaram')
        aviao.append(fortwo[0])
        aviao.append(fortwo[1])
        fortwo.clear()
        print(f'O {lista_passageiros[1]} embarca no fortwo')
        fortwo.append(lista_passageiros[1])
        aviao.remove('Chefe de serviço')
        print(f'Estão no avião {aviao}')
        print(f'O {fortwo[0]} retorna para o terminal de embarque dirigindo o carro')
        time.sleep(1)
    elif viagem == 7:
        passageiros_fortwo()
        print(f'O fortwo chegou ao terminal de embarque e o {lista_passageiros[0]} embarcou')
        fortwo.append(lista_passageiros[0])
        print(f'Estão no fortwo {fortwo}')
        terminal.clear()
        print('O terminal de embarque finalmente está vazio')
        print(f'Fortwo saiu em direção ao avião')
        time.sleep(1)
        print(f'O fortwo chegou ao avião e o {fortwo[0]} e o {fortwo[1]} desembarcaram')
        aviao.append(fortwo[0])
        aviao.append(fortwo[1])
        fortwo.clear()
        print(f'Estão no avião {aviao}')
        print('Todos os passageiros já estão a bordo do avião')

